name: SCTP Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sctp-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SCTP
      run: |
        sudo apt-get update
        sudo apt-get install -y lksctp-tools
        sudo modprobe sctp

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run SCTP tests
      run: |
        pytest test_sctp.py
